#!/usr/bin/env node
/**
 * Course material uploader.
 *
 * Usage:
 *   npm install
 *   cp .env.example .env      # then fill in SUPABASE_SERVICE_ROLE_KEY
 *   npm run upload-course -- <course-slug>
 *
 * What it does:
 *   1. Reads course-source/<slug>/meta.yaml
 *   2. Ensures the private Supabase Storage bucket exists
 *   3. Uploads every file listed in meta.yaml to <bucket>/<slug>/<path>
 *      with the correct Content-Type, upserting on re-runs
 *   4. Regenerates content/courses/<slug>/_index.md so the Hugo catalog
 *      stays in sync with meta.yaml
 *
 * Source files in course-source/ are gitignored — they live locally only.
 * Only meta-derived _index.md pages and this script are committed.
 */

import { readFile, writeFile, mkdir, stat } from 'node:fs/promises';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import yaml from 'js-yaml';
import mime from 'mime-types';

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function die(msg) {
  console.error(`\nError: ${msg}\n`);
  process.exit(1);
}

const slug = process.argv[2];
if (!slug) die('Missing course slug.\n  Usage: npm run upload-course -- <course-slug>');
if (!/^[a-z0-9-]+$/.test(slug)) die(`Invalid slug "${slug}". Use lowercase letters, digits, and hyphens only.`);

const { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, SUPABASE_COURSE_BUCKET = 'course-materials' } = process.env;
if (!SUPABASE_URL) die('SUPABASE_URL is not set. Copy .env.example to .env and fill it in.');
if (!SUPABASE_SERVICE_ROLE_KEY) die('SUPABASE_SERVICE_ROLE_KEY is not set. Copy .env.example to .env and fill it in.');

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false }
});

const courseDir = join(REPO_ROOT, 'course-source', slug);
const metaPath = join(courseDir, 'meta.yaml');

const meta = await readFile(metaPath, 'utf8').then(yaml.load).catch(() => {
  die(`Could not read ${metaPath}. Create the course folder and a meta.yaml (see scripts/meta.example.yaml).`);
});

if (!meta?.title) die(`meta.yaml is missing "title".`);
if (!Array.isArray(meta.files) || meta.files.length === 0) die(`meta.yaml must list at least one file under "files".`);

await ensureBucket(SUPABASE_COURSE_BUCKET);

const uploaded = [];
for (const entry of meta.files) {
  if (!entry?.path) die(`A file entry in meta.yaml is missing "path".`);
  const localPath = join(courseDir, entry.path);
  const fileStat = await stat(localPath).catch(() => die(`File not found: ${localPath}`));
  const bytes = await readFile(localPath);
  const contentType = mime.lookup(localPath) || 'application/octet-stream';
  const remotePath = `${slug}/${entry.path}`;

  const { error } = await supabase.storage
    .from(SUPABASE_COURSE_BUCKET)
    .upload(remotePath, bytes, { contentType, upsert: true, cacheControl: '3600' });

  if (error) die(`Upload failed for ${entry.path}: ${error.message}`);

  console.log(`  ✓ ${remotePath}  (${(fileStat.size / 1024).toFixed(1)} KB, ${contentType})`);
  uploaded.push({ ...entry, size: fileStat.size, contentType });
}

await writeCatalog(slug, meta, uploaded);

console.log(`\nDone. Uploaded ${uploaded.length} file(s) to bucket "${SUPABASE_COURSE_BUCKET}/${slug}".`);
console.log(`Catalog written to content/courses/${slug}.md`);

async function ensureBucket(name) {
  const { data, error } = await supabase.storage.getBucket(name);
  if (data) return;
  if (error && !/not found/i.test(error.message)) die(`Could not inspect bucket "${name}": ${error.message}`);

  const { error: createErr } = await supabase.storage.createBucket(name, { public: false });
  if (createErr) die(`Could not create private bucket "${name}": ${createErr.message}`);
  console.log(`Created private bucket "${name}".`);
}

async function writeCatalog(slug, meta, uploaded) {
  const outDir = join(REPO_ROOT, 'content', 'courses');
  await mkdir(outDir, { recursive: true });

  const frontMatter = {
    title: meta.title,
    description: meta.description ?? '',
    weight: meta.weight ?? 50,
    difficulty: meta.difficulty ?? null,
    duration: meta.duration ?? null,
    courseSlug: slug,
    bucket: SUPABASE_COURSE_BUCKET,
    generated: true,
    files: uploaded.map(f => ({
      path: f.path,
      title: f.title ?? f.path,
      description: f.description ?? '',
      kind: f.kind ?? 'lesson',
      contentType: f.contentType,
      size: f.size
    }))
  };

  const body = [
    '---',
    yaml.dump(frontMatter, { lineWidth: 120 }).trimEnd(),
    '---',
    '',
    '<!-- Generated by scripts/upload-course.js from course-source/' + slug + '/meta.yaml. Do not edit by hand. -->',
    ''
  ].join('\n');

  await writeFile(join(outDir, `${slug}.md`), body);
}
